export const TOGGLE_SWITCHES = 'TOGGLE_SWITCH';
export const SHOW_ERROR = 'SHOW_ERROR';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
