export const SET_SWITCHES = 'SET_SWITCHES';
export const SET_SWITCHES_STATE = 'SET_SWITCHES_STATE';
export const SHOW_ERROR = 'SHOW_ERROR';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
