export const TOGGLE_SWITCH = 'TOGGLE_SWITCH';
export const TOGGLE_ALL_SWITCHES = 'TOGGLE_ALL_SWITCHES';
export const SHOW_ERROR = 'SHOW_ERROR';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const LOADING = 'LOADING';
